zsh:
  - zsh-autosuggestions
  - zsh-syntax-highlighting
packages:
  linux:
    copr:
      - el-file4138/zotero
      - aquacash5/nerd-fonts
    dnf_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - code
      - fastfetch
      - fortune
      - starship
      - tldr
      - zsh
      - mozilla-fira-sans-fonts
      - mozilla-fira-mono-fonts
      - fira-code-nerd-fonts
      - victor-mono-nerd-fonts
      - python3-devel
      - pipx
      - zotero
      - gnome-tweaks
      - libappindicator-gtk3
      - python3-gpg
    flatpaks:
      - md.obsidian.Obsidian
      - com.spotify.Client
      - com.surfshark.Surfshark
      - org.inkscape.Inkscape
      - com.mattjakeman.ExtensionManager
      - sh.loft.devpod
      - com.github.tchx84.Flatseal
      - com.bitwarden.desktop
      - org.mozilla.Thunderbird
    web:
      - name: zoom
        url: https://zoom.us/client/latest/zoom_x86_64.rpm
      - name: dropbox
        url: https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2024.04.17-1.fc39.x86_64.rpm
      - name: warp-terminal
        url: https://app.warp.dev/download?package=rpm
    pipx:
      - cookiecutter
      - gnome-extensions-cli
    gnome_extensions:
      - nightthemeswitcher@romainvigier.fr
      - dash-to-panel@jderose9.github.com
      - blur-my-shell@aunetx
      - appindicatorsupport@rgcjonas.gmail.com
      - randomwallpaper@iflow.space
      - caffeine@patapon.info
      - tilingshell@ferrarodomenico.com
  darwin:
    taps:
      - r-lib/rig
      - koekeishiya/formulae
    brews:
      - gh
      - fastfetch
      - fortune
      - starship
      - python
      - pipx
      - tldr
      - mas
    casks:
      - docker
      - devpod
      - font-victor-mono-nerd-font
      - font-fira-sans
      - font-fira-mono
      - font-fira-code-nerd-font
      - inkscape
      - iina
      - obsidian
      - positron
      - spotify
      - stats
      - surfshark
      - the-unarchiver
      - visual-studio-code
      - warp
      - zoom
      - zotero
      - dropbox
    mas:
      - 1295203466 # Microsoft Remote Desktop
      - 937984704 # Amphetamine
      - 1352778147 # Bitwarden
      - 6469021132 # PDFgear
      - 310633997 # Whatsapp
    pipx:
      - radian
      - cookiecutter
