zsh:
  - zsh-autosuggestions
  - zsh-syntax-highlighting
packages:
  ubuntu:
    brews:
      - gh
      - fastfetch
      - fortune
      - starship
      - python
      - pipx
      - zoxide
      - eza
      - fzf
    apt_packages:
      - zsh
    pipx:
      - cookiecutter
  fedora:
    copr:
      - atim/starship
      - aquacash5/nerd-fonts
      - alternateved/eza
    dnf_packages:
      - starship
      - fastfetch
      - fortune
      - zoxide
      - eza
      - fira-code-nerd-fonts
      - victor-mono-nerd-fonts
      - fzf
      - zsh
  darwin:
    brews:
      - gh
      - fastfetch
      - fortune
      - starship
      - python
      - pipx
      - mas
      - zoxide
      - eza
      - fzf
    casks:
      - docker
      - devpod
      - font-victor-mono-nerd-font
      - font-fira-sans
      - font-fira-mono
      - font-fira-code-nerd-font
      - inkscape
      - iina
      - obsidian
      - positron
      - spotify
      - stats
      - surfshark
      - the-unarchiver
      - visual-studio-code
      - warp
      - zoom
      - zotero
      - dropbox
      - google-chrome
      - utm
    mas:
      - 1295203466 # Microsoft Remote Desktop
      - 937984704 # Amphetamine
      - 6469021132 # PDFgear
      - 310633997 # Whatsapp
    pipx:
      - cookiecutter
